// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniFrota.Context;

#nullable disable

namespace MiniFrota.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniFrota.Models.Admistrador", b =>
                {
                    b.Property<int>("AdmistradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmistradorId"));

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("AdmistradorId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("Admistradores");
                });

            modelBuilder.Entity("MiniFrota.Models.Combustivel", b =>
                {
                    b.Property<int>("CombustivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CombustivelId"));

                    b.Property<DateTime>("DataAbastecimento")
                        .HasColumnType("datetime2");

                    b.Property<long>("KmAbastecimentoAnterior")
                        .HasColumnType("bigint");

                    b.Property<long>("KmAtual")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoCombustivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorCombustivel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalAbastecimentoMes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CombustivelId");

                    b.ToTable("Combustiveis");
                });

            modelBuilder.Entity("MiniFrota.Models.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MultaAno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAbastecimentoAno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEmplacamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalManutencao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSeguro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("MiniFrota.Models.Manutencao", b =>
                {
                    b.Property<int>("ManutencaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManutencaoId"));

                    b.Property<DateTime>("DataProximaManutencao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaManutencao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoServico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorManutencao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ManutencaoId");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("MiniFrota.Models.Motorista", b =>
                {
                    b.Property<int>("MotoristaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotoristaId"));

                    b.Property<int?>("AdmistradorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("NumeroCnh")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VeiculoPlaca")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("MotoristaId");

                    b.HasIndex("AdmistradorId");

                    b.HasIndex("VeiculoPlaca");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("MiniFrota.Models.Multa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMulta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gravidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotoristaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VeicPlaca")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeicPlaca");

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("MiniFrota.Models.Seguro", b =>
                {
                    b.Property<int>("SeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguroId"));

                    b.Property<long>("CNPJ")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FimVigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Franquia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCorretoraSeguros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeSeguradora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumeroApolice")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorFranquia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSeguro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SeguroId");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("MiniFrota.Models.Sinistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.ToTable("Sinistros");
                });

            modelBuilder.Entity("MiniFrota.Models.Veiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CombustivelId")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Locado")
                        .HasColumnType("bit");

                    b.Property<int?>("ManutencaoId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeLocadora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("int");

                    b.HasKey("Placa");

                    b.HasIndex("CombustivelId");

                    b.HasIndex("ManutencaoId");

                    b.HasIndex("SeguroId");

                    b.ToTable("Veiculos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MiniFrota.Models.Emplacamento", b =>
                {
                    b.HasBaseType("MiniFrota.Models.Veiculo");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorEmplacamento")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Emplacamento");
                });

            modelBuilder.Entity("MiniFrota.Models.Admistrador", b =>
                {
                    b.HasOne("MiniFrota.Models.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId");

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("MiniFrota.Models.Motorista", b =>
                {
                    b.HasOne("MiniFrota.Models.Admistrador", null)
                        .WithMany("Motoristas")
                        .HasForeignKey("AdmistradorId");

                    b.HasOne("MiniFrota.Models.Veiculo", null)
                        .WithMany("Motoristas")
                        .HasForeignKey("VeiculoPlaca");
                });

            modelBuilder.Entity("MiniFrota.Models.Multa", b =>
                {
                    b.HasOne("MiniFrota.Models.Motorista", "Mot")
                        .WithMany()
                        .HasForeignKey("MotoristaId");

                    b.HasOne("MiniFrota.Models.Veiculo", "Veic")
                        .WithMany("Multas")
                        .HasForeignKey("VeicPlaca");

                    b.Navigation("Mot");

                    b.Navigation("Veic");
                });

            modelBuilder.Entity("MiniFrota.Models.Sinistro", b =>
                {
                    b.HasOne("MiniFrota.Models.Seguro", "Seg")
                        .WithMany()
                        .HasForeignKey("SeguroId");

                    b.Navigation("Seg");
                });

            modelBuilder.Entity("MiniFrota.Models.Veiculo", b =>
                {
                    b.HasOne("MiniFrota.Models.Combustivel", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("CombustivelId");

                    b.HasOne("MiniFrota.Models.Manutencao", "Manut")
                        .WithMany("Veiculos")
                        .HasForeignKey("ManutencaoId");

                    b.HasOne("MiniFrota.Models.Seguro", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("SeguroId");

                    b.Navigation("Manut");
                });

            modelBuilder.Entity("MiniFrota.Models.Admistrador", b =>
                {
                    b.Navigation("Motoristas");
                });

            modelBuilder.Entity("MiniFrota.Models.Combustivel", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("MiniFrota.Models.Manutencao", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("MiniFrota.Models.Seguro", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("MiniFrota.Models.Veiculo", b =>
                {
                    b.Navigation("Motoristas");

                    b.Navigation("Multas");
                });
#pragma warning restore 612, 618
        }
    }
}
